### ISSUE TITLE
Make `BigNumber` and instance of EuclideanRing

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/purescript-eth-core#9]
We have `divide` here: https://github.com/f-o-a-m/purescript-eth-core/blob/master/src/Network/Ethereum/Core/BigNumber.purs#L93

We can implement this instance similar to `euclideanRingNumber`: https://github.com/purescript/purescript-prelude/blob/master/src/Data/EuclideanRing.purs#L75

**Comment by iostat** [comment]
Bump. It's really annoying to have to use `Network.Ethereum.Core.BigNumber.divide` instead of just using the `div` / `/` operator from Prelude, and theres no reason we can't do this
